version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3307:3306"  #3307 -> 3306 mod later
    volumes:
      - mysql-data:/var/lib/mysql
      - ./dgs-db/init.sql:/docker-entrypoint-initdb.d/init.sql

  dgs-backend:
    build:
      context: ./dgs-backend
      dockerfile: Dockerfile
    ports:
      - "8085:8080"  # 85 -> 80 mod later
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always

  frontend:
    build:
      context: ./dgs-frontend
      dockerfile: Dockerfile

    ports:
      - "3000:80"
    depends_on:
      - dgs-backend

volumes:
  mysql-data: